#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         0
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_schme spiral
bspc config initial_polarity first_child
bspc config removal_adjustment true
bspc config split_ratio         0.5

bspc config normal_border_color "#0F1C22"
bspc config focused_border_color "#CBFAFF"
bspc config focus_follows_pointer true

#Autoset program window
bspc rule -a discord desktop='^2'
bspc rule -a Steam desktop='^3'
bspc rule -a obs desktop='^6'
bspc rule -a Firefox desktop='1'
bspc rule -a minecraft-launcher desktop='3'
bspc rule -a lunarclient desktop='3'

#Autostart
picom --config $HOME/.config/picom/picom.sample.conf --experimental-backends &
nitrogen --restore &
dunst &
$HOME/.config/polybar/launch.sh &
/bin/numlockx on &
#xfce4-panel &
