#! /bin/sh

chosen=$(printf " Config Files\n Browser Search\n Install Srcpkgs\n Bitwarden\n Calculator" | rofi -dmenu -i -theme-str '@import "rofimenus.rasi"' 20 -p '⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀' )

case "$chosen" in
  " Config Files") $HOME/Others/Scripts/rofi-files ;;
  " Browser Search") $HOME/Others/Scripts/rofi-search ;;
  " Install Srcpkgs") $HOME/Others/Scripts/srcscript-rofi ;;
  " Bitwarden") $HOME/Others/Scripts/rofi-rbw ;;
  " Calculator") $HOME/Others/Scripts/rofi-calc ;;
  *) exit 1 ;;
esac
